name: 8zer0s
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - poetry
  - ffmpeg
  - libsndfile
  - accelerate
  - argh
  - dacite
  - diffusers
  - flask
  - flask_cors
  - numpy
  - pillow
  - plotly
  - pydub
  - scipy
  - pytorch=*=*cuda*
  - pysoundfile
  - sox
  - torchaudio
  - transformers
  - cudatoolkit
  - pip
  - pip:
    - replicate
    - streamlit>=1.18.0
